// <auto-generated />
using System;
using IT610Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT610Project.Migrations
{
    [DbContext(typeof(BaseDbContext))]
    [Migration("20220715003142_NEFtoDatabase")]
    partial class NEFtoDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IT610Project.Models.NEF.AuditLogNewEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AuditLogTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFieldNewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFieldPreviousValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogNewEquipment");
                });

            modelBuilder.Entity("IT610Project.Models.NEF.AuditLogUserPermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AuditLogTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormField")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFieldNewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormFieldPreviousValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogUserPermissions");
                });

            modelBuilder.Entity("IT610Project.Models.NEF.NewEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<int>("Approver")
                        .HasColumnType("int");

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<int?>("BuildingKey")
                        .HasColumnType("int");

                    b.Property<string>("ControlNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Creator")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeptCharg2Key")
                        .HasColumnType("int");

                    b.Property<int>("DeptOwnerKey")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentCondKey")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentStatKey")
                        .HasColumnType("int");

                    b.Property<string>("FloorNo")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("InitialLoc")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LastLocation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("LocatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModelKey")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PurchaseCost")
                        .IsRequired()
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime?>("PurchaseDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("PurchaseOrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RoomNo")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Serial")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SoftwareRev")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("Submitted")
                        .HasColumnType("bit");

                    b.Property<int>("Submitter")
                        .HasColumnType("int");

                    b.Property<int?>("SystemKey")
                        .HasColumnType("int");

                    b.Property<int>("VendorKey")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WarrExpireLabor")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WarrExpirePart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NewEquipment");
                });

            modelBuilder.Entity("IT610Project.Models.NEF.UserPermissions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ApprovedRead")
                        .HasColumnType("bit");

                    b.Property<bool>("CreateDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CreateNew")
                        .HasColumnType("bit");

                    b.Property<bool>("CreateSave")
                        .HasColumnType("bit");

                    b.Property<int>("EmployeeCode")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeKey")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeName")
                        .HasColumnType("int");

                    b.Property<bool>("Login")
                        .HasColumnType("bit");

                    b.Property<bool>("Reject")
                        .HasColumnType("bit");

                    b.Property<bool>("SubmittedDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("SubmittedRead")
                        .HasColumnType("bit");

                    b.Property<bool>("SubmittedUpdate")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UserCreated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
